x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:1.13.1
    container_name: judge0_server
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - '2358:2358'
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - online-code-judge-network

  workers:
    image: judge0/judge0:1.13.1
    container_name: judge0_workers
    command: ['./scripts/workers']
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - online-code-judge-network

  db:
    image: postgres:16.2
    container_name: judge0_db
    env_file: judge0.conf
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
    networks:
      - online-code-judge-network

  redis:
    image: redis:7.2.4
    container_name: judge0_redis
    command:
      [
        'bash',
        '-c',
        'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always
    networks:
      - online-code-judge-network

  app:
    image: thobeogalaxy/judge-be:v1.0.17
    container_name: judge0_app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis
    <<: *default-logging
    restart: always
    networks:
      - online-code-judge-network

volumes:
  data:

networks:
  online-code-judge-network:
    driver: bridge
