name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get-version
        id: get-version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Deploy
        run: echo "Add your deployment steps here"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/judge-be:${{ env.VERSION }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.HOSTNAME }} << EOF
            sudo mkdir -p /usr/src/online-code-judge-be/
            cd /usr/src/online-code-judge-be/
            # Clone the repository if it doesn't exist, otherwise pull the latest changes
            if [ ! -d ".git" ]; then
              git clone https://github.com/NemCaBong/online-code-judge-be.git
            else
              git checkout main
              git reset --hard origin/main
              git pull origin main
            fi
            docker compose up -d
            docker image prune -af
          EOF
